In [1]:
from idlelib.debugobj import myrepr

import cv2 as cv
import numpy as np
import pandas as pd
import mymatch
import camera_calibration

In [2]:
path1 = 'obrazky/kytka/kytka_close.jpg'
path2 = 'obrazky/kytka/kytka_middleclose.jpg'
path3 = 'obrazky/kytka/kytka_middlefar.jpg'
path4 = 'obrazky/kytka/kytka_far.jpg'

pathlodka1 = 'obrazky/lodka/lodka1.jpg'
pathlodka2 = 'obrazky/lodka/lodka2.jpg'
pathlodka3 = 'obrazky/lodka/lodka3.jpg'
pathlodka4 = 'obrazky/lodka/lodka4.jpg'
pathlodka5 = 'obrazky/lodka/lodka5.jpg'

image1 = cv.imread(path1, cv.IMREAD_COLOR)
image2 = cv.imread(path2, cv.IMREAD_COLOR)
image3 = cv.imread(path3, cv.IMREAD_COLOR)
image4 = cv.imread(path4, cv.IMREAD_COLOR)

imagelodka1 = cv.imread(pathlodka1, cv.IMREAD_COLOR)
imagelodka2 = cv.imread(pathlodka2, cv.IMREAD_COLOR)
imagelodka3 = cv.imread(pathlodka3, cv.IMREAD_COLOR)
imagelodka4 = cv.imread(pathlodka4, cv.IMREAD_COLOR)
imagelodka5 = cv.imread(pathlodka5, cv.IMREAD_COLOR)


In [3]:
ret, mtx, dist, rvecs, tvecs = camera_calibration.calibrate_camera_chessboard()


Scanning image number: 1 of 46
Scanning image number: 2 of 46
Scanning image number: 3 of 46
Scanning image number: 4 of 46
Scanning image number: 5 of 46
Scanning image number: 6 of 46
Scanning image number: 7 of 46
Scanning image number: 8 of 46
Scanning image number: 9 of 46
Scanning image number: 10 of 46
Scanning image number: 11 of 46
Scanning image number: 12 of 46
Scanning image number: 13 of 46
Scanning image number: 14 of 46
Scanning image number: 15 of 46
Scanning image number: 16 of 46
Scanning image number: 17 of 46
Scanning image number: 18 of 46
Scanning image number: 19 of 46
Scanning image number: 20 of 46
Scanning image number: 21 of 46
Scanning image number: 22 of 46
Scanning image number: 23 of 46
Scanning image number: 24 of 46
Scanning image number: 25 of 46
Scanning image number: 26 of 46
Scanning image number: 27 of 46
Scanning image number: 28 of 46
Scanning image number: 29 of 46
Scanning image number: 30 of 46
Scanning image number: 31 of 46
Scanning image nu

In [4]:
mtx

array([[3.38156901e+03, 0.00000000e+00, 1.19630922e+03],
       [0.00000000e+00, 3.34287464e+03, 2.30534856e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [5]:
dist

array([[ 0.19749594, -0.71716753,  0.02145782,  0.01090343,  0.78578573]])

In [6]:
h,  w = image1.shape[:2]
newcameramtx, roi = cv.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

In [7]:
newcameramtx

array([[3.34512789e+03, 0.00000000e+00, 1.22011664e+03],
       [0.00000000e+00, 3.34527354e+03, 2.37726634e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [8]:
# Load the image
image_path = "obrazky/kytka/kytka_far.jpg"
image = cv.imread(image_path, cv.IMREAD_COLOR)
h, w = image.shape[:2]
new_camera_matrix, _ = cv.getOptimalNewCameraMatrix(mtx, dist, (w, h), 1, (w, h))
undistorted_image = cv.undistort(image, mtx, dist, None, new_camera_matrix)
# Convert the image to grayscale
gray_image = cv.cvtColor(undistorted_image, cv.COLOR_BGR2GRAY)

# Apply Gaussian Blur to reduce noise
blurred_image = cv.GaussianBlur(gray_image, (5, 5), 0)

# Apply Canny Edge Detection
edges = cv.Canny(blurred_image, threshold1=50, threshold2=150)

# Create resizable windows for display
cv.namedWindow('Original Image', cv.WINDOW_NORMAL)
cv.namedWindow('Edge Detection', cv.WINDOW_NORMAL)

# Display the images
cv.imshow('Original Image', image)
cv.imshow('Edge Detection', edges)

# Wait for a key press and close the windows
cv.waitKey(0)
cv.destroyAllWindows()


In [10]:
img1 = imagelodka1
img2 = imagelodka2

h1, w1 = img1.shape[:2]
h2, w2 = img2.shape[:2]

new_camera_matrix1, _ = cv.getOptimalNewCameraMatrix(mtx, dist, (w1, h1), 1, (w1, h1))
undistorted_image1 = cv.undistort(img1, mtx, dist, None, new_camera_matrix1)

new_camera_matrix2, _ = cv.getOptimalNewCameraMatrix(mtx, dist, (w2, h2), 1, (w2, h2))
undistorted_image2 = cv.undistort(img2, mtx, dist, None, new_camera_matrix2)


# Convert to grayscale
gray1 = cv.cvtColor(undistorted_image1, cv.COLOR_BGR2GRAY)
gray2 = cv.cvtColor(undistorted_image2, cv.COLOR_BGR2GRAY)

# Apply edge detection
edges1 = cv.Canny(gray1, threshold1=50, threshold2=150)
edges2 = cv.Canny(gray2, threshold1=50, threshold2=150)

# ORB feature detector
sift = cv.SIFT_create()

# Detect keypoints and descriptors
keypoints1, descriptors1 = sift.detectAndCompute(edges1, None)
keypoints2, descriptors2 = sift.detectAndCompute(edges2, None)

# Match features using BFMatcher
bf = cv.BFMatcher(cv.NORM_L2, crossCheck=True)
matches = bf.match(descriptors1, descriptors2)

# Sort matches by distance (lower is better)
matches = sorted(matches, key=lambda x: x.distance)

# Draw the top matches
matched_image = cv.drawMatches(img1, keypoints1, img2, keypoints2, matches[:50], None, flags=cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

# Create resizable windows for display
cv.namedWindow('Matched Features', cv.WINDOW_NORMAL)

# Display the result
cv.imshow('Matched Features', matched_image)
cv.imwrite('MatchedFeatures.jpg', matched_image)
cv.waitKey(0)
cv.destroyAllWindows()


In [25]:
def analyze2images(image1, image2):
    h1, w1 = image1.shape[:2]
    h2, w2 = image2.shape[:2]
    
    new_camera_matrix1, _ = cv.getOptimalNewCameraMatrix(mtx, dist, (w1, h1), 1, (w1, h1))
    undistorted_image1 = cv.undistort(image1, mtx, dist, None, new_camera_matrix1)
    
    new_camera_matrix2, _ = cv.getOptimalNewCameraMatrix(mtx, dist, (w2, h2), 1, (w2, h2))
    undistorted_image2 = cv.undistort(image2, mtx, dist, None, new_camera_matrix2)
    
    # Convert to grayscale
    gray1 = cv.cvtColor(undistorted_image1, cv.COLOR_BGR2GRAY)
    gray2 = cv.cvtColor(undistorted_image2, cv.COLOR_BGR2GRAY)
    
    # Apply edge detection
    edges1 = cv.Canny(gray1, threshold1=50, threshold2=150)
    edges2 = cv.Canny(gray2, threshold1=50, threshold2=150)
    
    # ORB feature detector
    orb = cv.SIFT_create()
    
    # Detect keypoints and descriptors
    keypoints1, descriptors1 = orb.detectAndCompute(edges1, None)
    keypoints2, descriptors2 = orb.detectAndCompute(edges2, None)
    
    # Match features using BFMatcher
    bf = cv.BFMatcher(cv.NORM_L2, crossCheck=True)
    matches = bf.match(descriptors1, descriptors2)
    
    # Sort matches by distance (lower is better)
    matches = sorted(matches, key=lambda x: x.distance)
    
    # Extract matched feature coordinates
    matched_features = []
    for match in matches:
        # Query and train indices
        idx1 = match.queryIdx
        idx2 = match.trainIdx
    
        # Get keypoint coordinates
        x1, y1 = keypoints1[idx1].pt  # Coordinates in image1
        x2, y2 = keypoints2[idx2].pt  # Coordinates in image2
    
        # Append to list
        matched_features.append({
            "Image1_X": x1,
            "Image1_Y": y1,
            "Image2_X": x2,
            "Image2_Y": y2,
            "Distance": match.distance
        })
    
    # Convert to Pandas DataFrame
    df = pd.DataFrame(matched_features)
    
    
    # Optionally visualize matches
    matched_image = cv.drawMatches(image1, keypoints1, image2, keypoints2, matches[:50], None, flags=cv.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    
    # cv.namedWindow('Matched Features', cv.WINDOW_NORMAL)
    # cv.imshow('Matched Features', matched_image)
    # cv.waitKey(0)
    # cv.destroyAllWindows()
    df['Delta_X'] = df['Image2_X'] - df['Image1_X']
    df['Delta_Y'] = df['Image2_Y'] - df['Image1_Y']
    
    # Calculate the averages
    average_delta_x = df['Delta_X'].mean()
    average_delta_y = df['Delta_Y'].mean()
    
    # Add the magnitude of the distance as an extra metric (optional)
    df['Distance_Magnitude'] = (df['Delta_X']**2 + df['Delta_Y']**2)**0.5
    return df


z = f \cdot \frac{X}{x}





f_{\text{pixels}} = \frac{f_{\text{mm}} \cdot \text{sensor width/height in pixels}}{\text{sensor width/height in mm}}


In [26]:
fl = 28 #mm


In [24]:
def estimate_feature_distance(df, delta_d, focal_length):
    """
    Estimate the real-world distance to a feature using the shift in pixel coordinates.
    
    Parameters:
        df (pd.DataFrame): DataFrame containing Delta_X and Delta_Y columns.
        delta_d (float): Distance between the two camera positions (meters).
        focal_length (float): Focal length of the camera (in pixels).
    
    Returns:
        pd.Series: Estimated distances to each feature.
    """
    # Compute the total pixel shift for each feature
    df['Delta_p'] = (df['Delta_X']**2 + df['Delta_Y']**2)**0.5
    
    # Estimate the distance to each feature
    df['Estimated_Distance'] = (delta_d * focal_length) / df['Delta_p']
    
    return df[['Delta_X', 'Delta_Y', 'Delta_p', 'Estimated_Distance']]



In [52]:
# delta_d = 1.0  
# focal_length = 800  Focal length in pixels
# 
# results = estimate_feature_distance(df, delta_d, focal_length)
# print(results)

In [32]:

# Function to estimate distances for 20 random points and display them on the image
def visualize_distances(df, image_path, delta_d, focal_length):
    """
    Randomly selects 20 points, calculates distances, and overlays them on the image.
    
    Parameters:
        df (pd.DataFrame): DataFrame containing matched feature coordinates (Image1_X, Image1_Y, Delta_X, Delta_Y).
        image_path (str): Path to the image file.
        delta_d (float): Real-world distance between camera positions (e.g., meters).
        focal_length (float): Focal length of the camera (e.g., in pixels).
    """
    # Select 20 random points
    random_points = df.sample(n=20, replace=True).copy()

    # Compute the total pixel shift
    random_points['Delta_p'] = (random_points['Delta_X']**2 + random_points['Delta_Y']**2)**0.5

    # Estimate the real-world distance for the selected points
    random_points['Estimated_Distance'] = (delta_d * focal_length) / random_points['Delta_p']

    # Load the image
    image = cv.imread(image_path)
    if image is None:
        raise FileNotFoundError(f"Image not found at {image_path}")

    # Overlay the points and distances on the image
    for _, row in random_points.iterrows():
        x, y = int(row['Image1_X']), int(row['Image1_Y'])
        distance = row['Estimated_Distance']

        # Draw the point on the image
        cv.circle(image, (x, y), radius=5, color=(0, 255, 0), thickness=-1)

        # Add the distance text
        cv.putText(image, f"{distance:.2f}m", (x + 10, y - 10),
                    fontFace=cv.FONT_HERSHEY_SIMPLEX, fontScale=2, color=(255, 255, 255), thickness=3)

    # Display the image
    cv.namedWindow('Feature Distances', cv.WINDOW_NORMAL)
    cv.imwrite('DistanceFeatureskyticka.jpg', image)

    cv.imshow('Feature Distances', image)
    cv.waitKey(0)
    cv.destroyAllWindows()




In [34]:
# Example parameters
delta_d = 0.5
focal_length = 3460  
image_path = path1
df = analyze2images(image1, image2)
# Run the visualization function
visualize_distances(df, image_path, delta_d, focal_length)

In [21]:
import mymatch
obr1 = imagelodka1
obr2 = imagelodka2
edges1 = mymatch.edge_preprocess(obr1)
edges2 = mymatch.edge_preprocess(obr2)

keypointskaze1, descriptorskaze1 = mymatch.features_KAZE(edges1)
keypointskaze2, descriptorskaze2 = mymatch.features_KAZE(edges2)

keypointsorb1, descriptorsorb1 = mymatch.features_ORB(edges1)
keypointsorb2, descriptorsorb2 = mymatch.features_ORB(edges2)

keypointsift1, descriptorsift1 = mymatch.features_SIFT(edges1)
keypointsift2, descriptorssift2 = mymatch.features_SIFT(edges2)

matcheskaze = mymatch.match(descriptorskaze1, descriptorskaze2)
matchesorb = mymatch.match(descriptorsorb1, descriptorsorb2)
matchesift = mymatch.match(descriptorsift1, descriptorssift2)

In [17]:
dfkaze = mymatch.matches_to_df(matcheskaze, keypointskaze1, keypointskaze2)
dforb = mymatch.matches_to_df(matchesorb, keypointsorb1, keypointsorb2)
dfsift = mymatch.matches_to_df(matchesift, keypointsift1, keypointsift2)

In [8]:
import mymatch

NameError: name 'keypoints1' is not defined

In [22]:
mymatch.save_images_matched_features(obr1, obr2, keypointsift1, keypointsift2, matchesift, 'lodmatchedSift.jpg')
mymatch.save_images_matched_features(obr1, obr2, keypointsorb1, keypointsorb2, matchesorb, 'lodmatchedOrb.jpg')
mymatch.save_images_matched_features(obr1, obr2, keypointskaze1, keypointskaze2, matcheskaze, 'lodmatchedKaze.jpg')

bakalářka: jak tohle funguje v souvislosti s neřesností v měření posunu.